apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
  namespace: demo
type: Opaque
stringData:
  DB_PASSWORD: "REPLACE_ME"
  JWT_SIGNING_KEY: "REPLACE_ME_DEV_SIGNING_KEY_32CHARS_MIN"
  APP_ENCRYPTION_KEY: "REPLACE_ME_APP_KEY"
