apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: demo
data:
  DB_HOST: "host.minikube.internal,1433"
  DB_NAME: "KubeCart_Orders"
  DB_USER: "sa"
  JWT_ISSUER: "kubecart-identity"
  JWT_AUDIENCE: "kubecart-api"
  CATALOG_SERVICE_URL: "http://catalog-service.demo.svc.cluster.local"
